config.load_autoconfig(False)
config.source('include/adblock.py')
config.source('include/bindings.py')
config.source('include/redirects.py')
config.source('include/search.py')
config.source('include/sites.py')
config.source('include/theme.py')
config.source('include/ui.py')
