c.completion.open_categories = ["bookmarks","history"]
c.confirm_quit = ['downloads']
c.content.fullscreen.window = True
c.content.prefers_reduced_motion = True
c.content.user_stylesheets = ['css/adblock.css', 'css/ao3.css', 'css/laserwave.css', 'css/twitter_dark.css', 'css/user.css']
c.fonts.default_size = '14pt'
c.qt.highdpi = True
c.tabs.show = 'multiple'
c.window.hide_decoration = True
c.zoom.default = 145
