[budgie-panel]
builtin-theme=false
confirm-remove-applet=false
dark-theme=true
migration-level=1
panels=['9bab0f82-7375-11ec-bbff-a864f1bbee5f']

[budgie-panel/applets/{7e3fdf9e-2f87-11ed-8771-a864f1bbee5f}]
alignment='start'
name='System Tray'
position=3

[budgie-panel/applets/{8e4a9598-7edc-11ec-93a3-a864f1bbee5f}]
alignment='start'
name='Workspace Switcher'
position=1

[budgie-panel/applets/{9bd3c364-7375-11ec-bbff-a864f1bbee5f}]
alignment='center'
name='System Tray'
position=3

[budgie-panel/applets/{9be4a0da-7375-11ec-bbff-a864f1bbee5f}]
alignment='start'
name='Clock'
position=0

[budgie-panel/applets/{bee913aa-8256-11ec-83c0-a864f1bbee5f}]
alignment='start'
name='Status Indicator'
position=2

[budgie-panel/applets/{c2dc2d46-57ab-11ed-b143-a864f1bbee5f}]
alignment='start'
name='User Indicator'
position=4

[budgie-panel/instance/status/{bee913aa-8256-11ec-83c0-a864f1bbee5f}]
spacing=0

[budgie-panel/instance/tray/{7e3fdf9e-2f87-11ed-8771-a864f1bbee5f}]
spacing=0

[budgie-panel/instance/tray/{9bd3c364-7375-11ec-bbff-a864f1bbee5f}]
spacing=0

[budgie-panel/instance/workspaces/{8e4a9598-7edc-11ec-93a3-a864f1bbee5f}]
addbutton-visibility='never'
item-size-multiplier='1.0'

[budgie-panel/panels/{9bab0f82-7375-11ec-bbff-a864f1bbee5f}]
applets=['bee913aa-8256-11ec-83c0-a864f1bbee5f', 'c2dc2d46-57ab-11ed-b143-a864f1bbee5f', '9be4a0da-7375-11ec-bbff-a864f1bbee5f', '8e4a9598-7edc-11ec-93a3-a864f1bbee5f', '7e3fdf9e-2f87-11ed-8771-a864f1bbee5f']
autohide='intelligent'
dock-mode=true
enable-shadow=true
location='top'
size=22
theme-regions=false
transparency='none'

[budgie-raven]
allow-volume-overdrive=true
show-calendar-widget=false
show-power-strip=true

[budgie-wm]
clear-notifications=['<Shift><Super>c']
toggle-notifications=@as []

[clock/instance/clock/{9be4a0da-7375-11ec-bbff-a864f1bbee5f}]
custom-format='%-d|%-I:%M'
use-custom-format=true

[software-center]
check-updates=false
fetch-media=false
