[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/']
www=['<Super>q']

[custom-keybindings/custom0]
binding='<Super>Return'
command='kitty'
name='Kitty'

[custom-keybindings/custom1]
binding='<Super>d'
command='fish -c launcher'
name='Launcher'

[custom-keybindings/custom10]
binding='<Super>k'
command='keepassxc'
name='KeepassXC'

[custom-keybindings/custom2]
binding='<Shift><Super>s'
command='budgie-control-center'
name='Settings'

[custom-keybindings/custom3]
binding='<Super>s'
command='spectacle'
name='Screenshot'

[custom-keybindings/custom4]
binding='<Shift><Super>d'
command='kitty discordo'
name='Discord'

[custom-keybindings/custom5]
binding='<Super>g'
command='kitty gurk'
name='Gurk'

[custom-keybindings/custom6]
binding='<Super>n'
command='netsurf-gtk3'
name='Netsurf'

[custom-keybindings/custom7]
binding='<Super>m'
command='kitty musikcube'
name='Musikcube'

[custom-keybindings/custom8]
binding='<Shift><Super>o'
command="fish -c 'open (fd | rofi -dmenu -i)'"
name='Open'

[custom-keybindings/custom9]
binding='<Super>c'
command='kitty fish -c "exec nnn"'
name='Files'
