// ==UserScript==
// @name          Discord - Arc Dark
// @namespace     http://userstyles.org
// @description	  A theme for Discord that changes the colors to match the Arc Dark GTK scheme.
// @author        sans
// @homepage      https://userstyles.org/styles/127986
// @include       http://discordapp.com/*
// @include       https://discordapp.com/*
// @include       http://*.discordapp.com/*
// @include       https://*.discordapp.com/*
// @run-at        document-start
// @version       0.20180805060411
// ==/UserScript==
(function() {var css = [
	"::-webkit-scrollbar-track-piece {",
	"    background-color: transparent !important;",
	"    border-color: transparent !important; }",
	"",
	"  ::-webkit-scrollbar-thumb {",
	"    background-color: #1B2428 !important;",
	"    border-color: #1B2428 !important; }",
	"",
	"  [class*=\'markup-\'] a,",
	"  .sample-link {",
	"    color: #5294E2 !important; }",
	"",
	"  [style*=\'background: rgb(114, 137, 218)\'] {",
	"    background: #5294E2 !important; }",
	"",
	"  [style*=\'background-color: rgb(114, 137, 218)\'] {",
	"    background-color: #5294E2 !important; }",
	"",
	"  [style*=\'border-color: rgb(114, 137, 218)\'] {",
	"    border-color: #5294E2 !important; }",
	"",
	"  [style*=\'color: rgb(114, 137, 218)\'] {",
	"    color: #5294E2 !important; }",
	"",
	"  [class*=\'lookFilled-\'][class*=\'colorBrand-\'] {",
	"    background-color: #5294E2 !important; }",
	"    [class*=\'lookFilled-\'][class*=\'colorBrand-\']:hover {",
	"      background-color: #3c86de !important; }",
	"",
	"  [class*=\'lookGhost-\'][class*=\'colorBrand-\'] {",
	"    color: #5294E2 !important; }",
	"",
	"  [class*=\'checked-\'] {",
	"    background-color: transparent !important; }",
	"",
	"  [class*=\'checked-\'][style*=\'border-color: rgb(114, 137, 218)\'] polyline {",
	"    stroke: #5294E2 !important; }",
	"",
	"  [class*=\'valueUnchecked\'] {",
	"    background-color: #1B2428 !important; }",
	"",
	"  [class*=\'valueChecked-\'] {",
	"    background-color: #5294E2 !important; }",
	"",
	"  [class^=\'barFill-\']:not([style*=\'background\']) {",
	"    background-color: #5294E2 !important; }",
	"",
	"  [class*=\'input-\']:focus, [class*=\'input-\'][class*=\'focused-\'],",
	"  [class*=\'prefixInput-\']:focus,",
	"  [class*=\'prefixInput-\'][class*=\'focused-\'] {",
	"    border-color: #5294E2 !important; }",
	"",
	"  [class^=\'select-\'],",
	"  .Select-control {",
	"    background-color: #1B2428 !important;",
	"    border-color: #1B2428 !important; }",
	"    [class^=\'select-\'] ::-webkit-scrollbar-track-piece,",
	"    .Select-control ::-webkit-scrollbar-track-piece {",
	"      background-color: #1B2428 !important; }",
	"    [class^=\'select-\'] ::-webkit-scrollbar-thumb,",
	"    .Select-control ::-webkit-scrollbar-thumb {",
	"      background-color: #263238 !important; }",
	"",
	"  .Select-option {",
	"    background-color: #1B2428 !important; }",
	"    .Select-option.is-focused {",
	"      background-color: #222D32 !important; }",
	"",
	"  [class^=\'popoutList-\'] {",
	"    background: #222D32 !important; }",
	"    [class^=\'popoutList-\'] [class*=\'selectableItem-\']:not([class*=\'selected-\']):hover {",
	"      background-color: #1B2428 !important; }",
	"    [class^=\'popoutList-\'] ::-webkit-scrollbar-track-piece {",
	"      background-color: #222D32 !important; }",
	"",
	"  [class^=\'botTagRegular-\'] {",
	"    background: #708090 !important; }",
	"",
	"  .tooltip {",
	"    background-color: #5294E2 !important;",
	"    color: #fff !important; }",
	"    .tooltip.tooltip-top::after {",
	"      border-top-color: #5294E2 !important; }",
	"    .tooltip.tooltip-bottom::after {",
	"      border-bottom-color: #5294E2 !important; }",
	"    .tooltip.tooltip-left::after {",
	"      border-left-color: #5294E2 !important; }",
	"    .tooltip.tooltip-right::after {",
	"      border-right-color: #5294E2 !important; }",
	"",
	"  [class^=\'contextMenu-\'] {",
	"    background: #1B2428 !important; }",
	"    [class^=\'contextMenu-\'] [class^=\'itemGroup-\'] {",
	"      border-color: #222D32 !important; }",
	"    [class^=\'contextMenu-\'] [class^=\'item-\']:hover {",
	"      background: #222D32 !important; }",
	"    [class^=\'contextMenu-\'] [class*=\'itemSubMenu-\'] {",
	"      background-color: #1B2428 !important; }",
	"",
	"  [class^=\'keyboardShortcutsModal-\'] {",
	"    background-color: #222D32 !important; }",
	"",
	"  [class^=\'keybindDescription-\'] {",
	"    color: #d8d8d8 !important; }",
	"",
	"  [class^=\'keybindShortcut-\'] span {",
	"    background-color: #708090 !important;",
	"    color: #fff !important; }",
	"",
	"  [class^=\'quickswitcher-\'] {",
	"    background-color: #222D32 !important; }",
	"    [class^=\'quickswitcher-\'] input {",
	"      background-color: #1B2428 !important; }",
	"    [class^=\'quickswitcher-\'] [class^=\'resultFocused-\'] {",
	"      background-color: #1B2428 !important; }",
	"    [class^=\'quickswitcher-\'] ::-webkit-scrollbar-track {",
	"      background-color: transparent !important; }",
	"",
	"  [class^=\'regionSelectInner-\'] {",
	"    background-color: #1B2428 !important;",
	"    border-color: #1B2428 !important; }",
	"",
	"  [class^=\'regionSelect-\'] button {",
	"    background-color: #5294E2 !important;",
	"    border-color: #5294E2 !important;",
	"    color: #d8d8d8 !important; }",
	"    [class^=\'regionSelect-\'] button:hover {",
	"      background-color: #3c86de !important; }",
	"",
	"  [class^=\'regionSelectModal-\'] {",
	"    background: #222D32 !important; }",
	"",
	"  [class^=\'regionSelectModalHeader-\'] {",
	"    color: #5294E2 !important; }",
	"",
	"  [class^=\'regionSelectModalOption-\'] {",
	"    background-color: #1B2428 !important;",
	"    border-color: #1B2428 !important; }",
	"    [class^=\'regionSelectModalOption-\']:hover {",
	"      border-color: #5294E2 !important; }",
	"",
	"  .avatar-uploader-inner {",
	"    background-color: #5294E2 !important;",
	"    border-color: #222D32 !important; }",
	"    .avatar-uploader-inner:hover {",
	"      background: #3c86de !important;",
	"      box-shadow: none !important; }",
	"",
	"  .avatar-uploader-indicator {",
	"    background-color: #d0cbc0 !important;",
	"    -webkit-filter: invert(100%);",
	"            filter: invert(100%); }",
	"",
	"  [class^=\'guildsWrapper-\'] {",
	"    background-color: #1B2428 !important; }",
	"    [class^=\'guildsWrapper-\'] ::-webkit-scrollbar-thumb {",
	"      background-color: #222D32 !important;",
	"      border-color: #222D32 !important; }",
	"",
	"  [class^=\'iconBadge-\'] {",
	"    background-color: #5294E2 !important; }",
	"",
	"  [class^=\'guild-\'] > [class*=\'badge-\'] {",
	"    background-color: #5294E2 !important; }",
	"  [class^=\'guild-\'] [class^=\'guildInner-\'] {",
	"    background-color: #222D32 !important; }",
	"    [class^=\'guild-\'] [class^=\'guildInner-\']::after {",
	"      background-color: #5294E2 !important; }",
	"  [class^=\'guild-\']:hover [class^=\'guildInner-\'], [class^=\'guild-\'][class*=\'selected-\'] [class^=\'guildInner-\'] {",
	"    background-color: #263238 !important; }",
	"",
	"  [class*=\'guildsAdd-\'] {",
	"    background: #1B2428 !important;",
	"    border-color: #263238 !important;",
	"    border-style: solid !important;",
	"    color: #d8d8d8 !important; }",
	"    [class*=\'guildsAdd-\']:hover {",
	"      border-color: #d8d8d8 !important; }",
	"",
	"  .form.deprecated header,",
	"  .form.deprecated h5 {",
	"    color: #5294E2 !important; }",
	"  .form.deprecated .form-inner {",
	"    background-color: #222D32 !important; }",
	"  .form.deprecated .action {",
	"    background: #1B2428 !important; }",
	"  .form.deprecated .or {",
	"    display: none !important; }",
	"  .form.deprecated .create .action-header {",
	"    color: #5294E2 !important; }",
	"  .form.deprecated .create .btn-primary {",
	"    background-color: #5294E2 !important; }",
	"    .form.deprecated .create .btn-primary:hover {",
	"      background-color: #3c86de !important; }",
	"  .form.deprecated input[type=\'text\'] {",
	"    background-color: #222D32 !important;",
	"    border-color: #1B2428 !important;",
	"    color: #d8d8d8 !important; }",
	"    .form.deprecated input[type=\'text\']:focus {",
	"      border-color: #5294E2 !important; }",
	"  .form.deprecated .form-actions {",
	"    background-color: #1B2428 !important;",
	"    border-color: #1B2428 !important; }",
	"  .form.deprecated .btn-default {",
	"    background-color: #1B2428 !important;",
	"    border-color: #1B2428 !important; }",
	"  .form.deprecated .btn-primary {",
	"    background-color: #5294E2 !important; }",
	"    .form.deprecated .btn-primary:hover {",
	"      background-color: #3c86de !important; }",
	"",
	"  .create-guild-container {",
	"    background-color: #1B2428 !important; }",
	"",
	"  [class*=\'unreadMentionsBar-\'] {",
	"    background-color: #5294E2 !important; }",
	"    [class*=\'unreadMentionsBar-\']:hover {",
	"      background-color: #3c86de !important; }",
	"",
	"  [class*=\'searchBar-\'] {",
	"    background-color: #222D32 !important; }",
	"",
	"  [class^=\'searchBarInner-\'] {",
	"    background-color: #1B2428 !important; }",
	"    [class^=\'searchBarInner-\'] input,",
	"    [class^=\'searchBarInner-\'] input::-webkit-input-placeholder {",
	"      color: #d8d8d8 !important; }",
	"    [class^=\'searchBarInner-\'] input,",
	"    [class^=\'searchBarInner-\'] input:-ms-input-placeholder {",
	"      color: #d8d8d8 !important; }",
	"    [class^=\'searchBarInner-\'] input,",
	"    [class^=\'searchBarInner-\'] input::-ms-input-placeholder {",
	"      color: #d8d8d8 !important; }",
	"    [class^=\'searchBarInner-\'] input,",
	"    [class^=\'searchBarInner-\'] input::placeholder {",
	"      color: #d8d8d8 !important; }",
	"",
	"  .public-DraftEditorPlaceholder-root {",
	"    color: #d8d8d8 !important; }",
	"",
	"  .private-channels .channel:hover a,",
	"  .private-channels .channel.selected a {",
	"    background-color: #263238 !important; }",
	"",
	"  .channel-name + [class^=\'wrapper-\'] {",
	"    background-color: #5294E2 !important; }",
	"",
	"  [class^=\'activityFeed-\'] {",
	"    background-color: #263238 !important; }",
	"",
	"  [class^=\'card-\'] [class*=\'cardHeader-\'] {",
	"    background-color: #1B2428 !important; }",
	"  [class^=\'card-\'] [class^=\'splashArt-\'] {",
	"    display: none !important; }",
	"  [class^=\'card-\'] > [class^=\'body-\'] {",
	"    background-color: #222D32 !important; }",
	"",
	"  #friends {",
	"    background-color: #263238 !important; }",
	"    #friends [class*=\'headerBar-\'],",
	"    #friends .friends-table,",
	"    #friends .friends-table-add {",
	"      background: #263238 !important; }",
	"    #friends .tab-bar-item-primary {",
	"      background-color: #5294E2 !important;",
	"      color: #fff !important; }",
	"      #friends .tab-bar-item-primary.selected {",
	"        background-color: #fff !important;",
	"        color: #5294E2 !important; }",
	"    #friends .tab-bar-item > [class^=\'wrapper-\'] {",
	"      background-color: #5294E2 !important; }",
	"    #friends .friends-table-add > [class^=\'wrapper-\'] {",
	"      background-color: #1B2428 !important; }",
	"    #friends [class^=\'addFriendInput-\']::-webkit-input-placeholder {",
	"      color: #d8d8d8 !important; }",
	"    #friends [class^=\'addFriendInput-\']:-ms-input-placeholder {",
	"      color: #d8d8d8 !important; }",
	"    #friends [class^=\'addFriendInput-\']::-ms-input-placeholder {",
	"      color: #d8d8d8 !important; }",
	"    #friends [class^=\'addFriendInput-\']::placeholder {",
	"      color: #d8d8d8 !important; }",
	"    #friends .friends-row:hover {",
	"      background: #222D32 !important; }",
	"    #friends .friends-action {",
	"      background-color: #1B2428 !important; }",
	"",
	"  [class*=\'popout-\'] {",
	"    background-color: #222D32 !important; }",
	"    [class*=\'popout-\'] [class*=\'friendSelected-\'] {",
	"      background-color: #263238 !important; }",
	"    [class*=\'popout-\'] [class*=\'checked-\'] {",
	"      border-color: #d8d8d8 !important; }",
	"      [class*=\'popout-\'] [class*=\'checked-\'] polyline {",
	"        stroke: #d8d8d8 !important; }",
	"    [class*=\'popout-\'] [class*=\'searchBarTag-\'] {",
	"      background: #263238 !important;",
	"      color: #d8d8d8 !important; }",
	"",
	"  [class*=\'video-\'] {",
	"    background-color: #1B2428 !important; }",
	"    [class*=\'video-\'] [class*=\'actions-\'] [class*=\'center-\'] {",
	"      background-color: #263238 !important;",
	"      border-color: #263238 !important; }",
	"    [class*=\'video-\'] [class^=\'callAvatarBorder-\']:not([class*=\'soundsharing-\']):not([class*=\'speaking\']) {",
	"      box-shadow: inset 0 0 0 2px #5294E2 !important; }",
	"",
	"  [class^=\'menu-\'] {",
	"    background-color: #1B2428 !important; }",
	"    [class^=\'menu-\'] [class^=\'item-\']:hover {",
	"      background-color: #263238 !important; }",
	"      [class^=\'menu-\'] [class^=\'item-\']:hover:not([class^=\'invite-\']) [class^=\'label-\'] {",
	"        color: #fff !important; }",
	"    [class^=\'menu-\'] [class*=\'invite-\'] {",
	"      color: #5294E2 !important; }",
	"      [class^=\'menu-\'] [class*=\'invite-\'] [class^=\'icon-\'] {",
	"        -webkit-filter: hue-rotate(-20deg) !important;",
	"                filter: hue-rotate(-20deg) !important; }",
	"    [class^=\'menu-\'] [class^=\'separator-\'] {",
	"      border-color: #1B2428 !important; }",
	"",
	"  [class^=\'channels-\'] > div:first-of-type {",
	"    background-color: #222D32 !important; }",
	"  [class^=\'channels-\'] > [class^=\'container-\'] {",
	"    background-color: #1B2428 !important; }",
	"",
	"  [class^=\'containerDragBefore-\']::before,",
	"  [class^=\'containerDragAfter-\']::after {",
	"    background-color: #5294E2; }",
	"",
	"  [class^=\'contentSelectedText\'],",
	"  [class^=\'contentHoveredText-\'],",
	"  [class^=\'contentHoveredVoice-\'] {",
	"    background-color: #263238 !important; }",
	"    [class^=\'contentSelectedText\'] [class^=\'iconSpacing-\'] > [class^=\'wrapper-\'],",
	"    [class^=\'contentHoveredText-\'] [class^=\'iconSpacing-\'] > [class^=\'wrapper-\'],",
	"    [class^=\'contentHoveredVoice-\'] [class^=\'iconSpacing-\'] > [class^=\'wrapper-\'] {",
	"      background-color: #5294E2 !important; }",
	"",
	"  [class^=\'contentUnreadText-\'] [class^=\'iconSpacing-\'] > [class^=\'wrapper-\'] {",
	"    background-color: #5294E2 !important; }",
	"",
	"  [class^=\'inviteRow-\']:hover {",
	"    background-color: #1B2428 !important; }",
	"",
	"  [class^=\'avatarSpeaking-\'] {",
	"    box-shadow: 0 0 0 2px #5294E2, inset 0 0 0 1.5px #222D32 !important; }",
	"",
	"  [class^=\'contentDefaultVoice-\'] [class^=\'flex-\'] [class^=\'wrapper-\'],",
	"  [class^=\'contentConnectedVoice-\'] [class^=\'flex-\'] [class^=\'wrapper-\'] {",
	"    background-color: #1B2428; }",
	"",
	"  [class*=\'popouts-\'] > [class*=\'popout-\'] > [class^=\'container-\'] header {",
	"    background-color: #1B2428 !important; }",
	"  [class*=\'popouts-\'] > [class*=\'popout-\'] > [class^=\'container-\'] section {",
	"    background-color: #222D32 !important; }",
	"    [class*=\'popouts-\'] > [class*=\'popout-\'] > [class^=\'container-\'] section::after {",
	"      border-top-color: #222D32 !important; }",
	"",
	"  [class^=\'titleWrapper-\'] [class*=\'title-\'] {",
	"    background: #263238 !important; }",
	"",
	"  [name=\'NotificationBellOff\'] path:last-child {",
	"    stroke: #5294E2; }",
	"",
	"  [class*=\'themedPopout-\'] {",
	"    background-color: #1B2428 !important; }",
	"    [class*=\'themedPopout-\'] [class^=\'header-\'] {",
	"      background-color: #222D32 !important; }",
	"    [class*=\'themedPopout-\'] [class^=\'messageGroupWrapper-\'] {",
	"      background-color: #263238 !important; }",
	"      [class*=\'themedPopout-\'] [class^=\'messageGroupWrapper-\'] [class^=\'jumpButton-\'] {",
	"        background-color: #1B2428 !important;",
	"        color: #d8d8d8 !important; }",
	"      [class*=\'themedPopout-\'] [class^=\'messageGroupWrapper-\']:hover [class^=\'actionButtons-\'] {",
	"        background-color: #263238 !important;",
	"        box-shadow: none !important; }",
	"",
	"  [class^=\'searchFilter-\'],",
	"  [class^=\'searchAnswer-\'] {",
	"    background-color: #1B2428 !important; }",
	"",
	"  [class^=\'searchPopout-\'] {",
	"    background-color: #222D32 !important; }",
	"    [class^=\'searchPopout-\'] [class^=\'option-\'] [class^=\'answer-\'] {",
	"      color: #d8d8d8 !important; }",
	"    [class^=\'searchPopout-\'] [class^=\'option-\']:hover, [class^=\'searchPopout-\'] [class^=\'option-\'][class*=\'selected-\'] {",
	"      background-color: #1B2428 !important; }",
	"      [class^=\'searchPopout-\'] [class^=\'option-\']:hover [class^=\'filter-\'], [class^=\'searchPopout-\'] [class^=\'option-\'][class*=\'selected-\'] [class^=\'filter-\'] {",
	"        color: #fff !important; }",
	"",
	"  .search-results-wrap {",
	"    background-color: #222D32 !important; }",
	"",
	"  .search-header {",
	"    background-color: #1B2428 !important; }",
	"",
	"  .search-results-wrap .channel-name {",
	"    background-color: #222D32 !important; }",
	"",
	"  .search-result::before,",
	"  .search-result::after {",
	"    background-image: none !important; }",
	"",
	"  .search-result .hit {",
	"    background-color: #263238 !important;",
	"    border-color: #1B2428 !important;",
	"    box-shadow: none !important; }",
	"",
	"  .search-result .jump-button {",
	"    background-color: #1B2428 !important; }",
	"",
	"  .highlight {",
	"    background-color: rgba(82, 148, 226, 0.15) !important; }",
	"",
	"  .react-datepicker,",
	"  .react-datepicker__header {",
	"    background-color: #222D32 !important; }",
	"",
	"  .react-datepicker__day:hover {",
	"    background-color: #5294E2 !important; }",
	"",
	"  .react-datepicker__day--outside-month,",
	"  .react-datepicker__day--disabled {",
	"    background-color: #1B2428 !important;",
	"    pointer-events: none !important; }",
	"",
	"  .react-datepicker__day--selected::after,",
	"  [class^=\'datePickerHint-\'] > [class^=\'hintValue-\'] {",
	"    background-color: #5294E2 !important; }",
	"",
	"  [class^=\'messagesWrapper-\'] {",
	"    background-color: #263238 !important; }",
	"",
	"  [class^=\'newMessagesBar-\'] {",
	"    background-color: #5294E2 !important; }",
	"",
	"  [class^=\'welcomeMessage-\'] h1 {",
	"    color: #5294E2 !important; }",
	"",
	"  .mention:not([style*=\'background\']),",
	"  [class*=\'wrapperHover-\'][role=\'button\'] {",
	"    background-color: rgba(82, 148, 226, 0.15) !important;",
	"    color: #5294E2 !important; }",
	"    .mention:not([style*=\'background\']):hover,",
	"    [class*=\'wrapperHover-\'][role=\'button\']:hover {",
	"      background-color: rgba(60, 134, 222, 0.15) !important;",
	"      color: #3c86de !important; }",
	"",
	"  [class*=\'wrapper-\'][role=\'button\'] {",
	"    color: #5294E2 !important; }",
	"",
	"  [class^=\'messages-\'] [class^=\'containerCozy-\'] > [class^=\'wrapper-\'],",
	"  [class^=\'messages-\'] [class^=\'containerCompact-\'] > [class^=\'wrapper-\'] {",
	"    background-color: #222D32 !important;",
	"    border-color: #222D32 !important; }",
	"    [class^=\'messages-\'] [class^=\'containerCozy-\'] > [class^=\'wrapper-\'] button,",
	"    [class^=\'messages-\'] [class^=\'containerCompact-\'] > [class^=\'wrapper-\'] button {",
	"      background-color: #1B2428 !important;",
	"      border-color: #1B2428 !important; }",
	"    [class^=\'messages-\'] [class^=\'containerCozy-\'] > [class^=\'wrapper-\'] [class*=\'lookFilled-\'],",
	"    [class^=\'messages-\'] [class^=\'containerCompact-\'] > [class^=\'wrapper-\'] [class*=\'lookFilled-\'] {",
	"      background-color: #5294E2 !important;",
	"      border-color: #5294E2 !important; }",
	"",
	"  [class^=\'divider-\'] span {",
	"    background-color: #263238 !important; }",
	"",
	"  [class*=\'dividerRed-\'] > div {",
	"    background-color: #5294E2 !important; }",
	"  [class*=\'dividerRed-\'] > span {",
	"    color: #5294E2 !important; }",
	"",
	"  [class*=\'isMentioned-\'] {",
	"    background: rgba(82, 148, 226, 0.15) !important; }",
	"",
	"  [class^=\'isMentionedCozy-\']::after {",
	"    border-color: #5294E2 !important; }",
	"",
	"  [class^=\'embedInner-\'] {",
	"    background-color: #222D32 !important;",
	"    border-color: #222D32 !important; }",
	"    [class^=\'embedInner-\'] [class*=\'embedTitleLink-\'] {",
	"      color: #5294E2 !important; }",
	"    [class^=\'embedInner-\'] [class^=\'embedDescription-\'] a {",
	"      color: #5294E2 !important; }",
	"",
	"  [class^=\'attachment-\'] {",
	"    background-color: #222D32 !important;",
	"    border-color: #222D32 !important; }",
	"",
	"  [class^=\'anchor-\'] {",
	"    color: #5294E2 !important; }",
	"",
	"  [class^=\'isLocalBot-\'] {",
	"    background: #263238 !important; }",
	"",
	"  [class*=\'markup-\'] code {",
	"    background: #1B2428 !important; }",
	"",
	"  [class^=\'dividerEnabled-\'] {",
	"    border-bottom-color: #263238 !important; }",
	"",
	"  [class^=\'chat-\'] > [class^=\'content-\'] {",
	"    background-color: #263238 !important; }",
	"  [class^=\'chat-\'] form {",
	"    background-color: #263238 !important; }",
	"",
	"  [class^=\'hasMore-\'] button {",
	"    background: #222D32 !important;",
	"    border-color: #222D32 !important;",
	"    color: #5294E2 !important; }",
	"",
	"  [class^=\'channelTextArea-\'] [class^=\'inner-\'],",
	"  [class^=\'channelTextAreaEnabledNoAttach-\'] [class^=\'innerEnabledNoAttach-\'] {",
	"    background-color: #222D32 !important; }",
	"",
	"  [class^=\'channelTextAreaDisabled\'] {",
	"    opacity: 1 !important; }",
	"    [class^=\'channelTextAreaDisabled\'] [class^=\'innerDisabled-\'] {",
	"      background-color: #263238 !important; }",
	"",
	"  [class^=\'emojiPicker-\'] {",
	"    background-color: #222D32 !important;",
	"    border-color: #1B2428 !important; }",
	"    [class^=\'emojiPicker-\'] [class^=\'dimmer-\'][class*=\'visible-\'] {",
	"      background-color: rgba(47, 52, 63, 0.9) !important; }",
	"    [class^=\'emojiPicker-\'] [class^=\'stickyHeader-\'] {",
	"      background-color: #1B2428 !important; }",
	"    [class^=\'emojiPicker-\'] ::-webkit-scrollbar-track {",
	"      background-color: #222D32 !important; }",
	"    [class^=\'emojiPicker-\'] [class^=\'item-\'][class*=\'selected-\'] {",
	"      border-color: #5294E2 !important; }",
	"",
	"  [class^=\'diversitySelector-\'] [class^=\'popout-\'] {",
	"    background-color: #1B2428 !important;",
	"    border-color: #1B2428 !important; }",
	"",
	"  [class^=\'emojiItem-\'][class*=\'selected-\'] {",
	"    background-color: #5294E2 !important; }",
	"",
	"  [class^=\'autocomplete-\']:not(.autocomplete-arrow-wrapper),",
	"  #autocomplete-popout {",
	"    background-color: #222D32 !important; }",
	"    [class^=\'autocomplete-\']:not(.autocomplete-arrow-wrapper) [class^=\'selectorSelected-\'],",
	"    [class^=\'autocomplete-\']:not(.autocomplete-arrow-wrapper) .selected,",
	"    #autocomplete-popout [class^=\'selectorSelected-\'],",
	"    #autocomplete-popout .selected {",
	"      background: #1B2428 !important; }",
	"    [class^=\'autocomplete-\']:not(.autocomplete-arrow-wrapper) ::-webkit-scrollbar-track-piece,",
	"    #autocomplete-popout ::-webkit-scrollbar-track-piece {",
	"      background: #222D32 !important; }",
	"",
	"  [class^=\'typing-\'] {",
	"    background-color: #263238 !important; }",
	"",
	"  [class^=\'uploadModal-\'] {",
	"    background-color: #263238 !important; }",
	"    [class^=\'uploadModal-\'] [class^=\'inner-\'] {",
	"      border-color: #1B2428 !important; }",
	"    [class^=\'uploadModal-\'] [class*=\'image-\'] {",
	"      border-color: #1B2428 !important; }",
	"    [class^=\'uploadModal-\'] [class*=\'content-\'] {",
	"      color: #d8d8d8 !important; }",
	"    [class^=\'uploadModal-\'] .button {",
	"      background-color: #1B2428 !important; }",
	"    [class^=\'uploadModal-\'] .button-primary {",
	"      background-color: #5294E2 !important;",
	"      color: #fff !important; }",
	"",
	"  [class*=\'members-\'] {",
	"    background-color: #222D32 !important; }",
	"",
	"  [class*=\'member-\']:hover [class^=\'content-\'],",
	"  [class*=\'member-\'].popout-open [class^=\'content-\'] {",
	"    background-color: #263238 !important; }",
	"",
	"  [class^=\'userPopout-\'] [class^=\'headerNormal-\'] {",
	"    background-color: #1B2428 !important; }",
	"  [class^=\'userPopout-\'] [class^=\'headerPlaying-\'] {",
	"    background-color: #5294E2 !important; }",
	"  [class^=\'userPopout-\'] [class^=\'body-\'],",
	"  [class^=\'userPopout-\'] [class^=\'footer-\'] {",
	"    background-color: #222D32 !important; }",
	"",
	"  [class^=\'note-\'] textarea:focus {",
	"    background-color: #1B2428 !important; }",
	"",
	"  [class^=\'quickMessage-\'] {",
	"    background-color: #1B2428 !important; }",
	"",
	"  [class^=\'backdrop-\'] + [class^=\'modal-\'] [class^=\'modal-\'] {",
	"    background-color: #222D32 !important; }",
	"  [class^=\'backdrop-\'] + [class^=\'modal-\'] [class^=\'topSectionNormal-\'] {",
	"    background-color: #1B2428 !important; }",
	"  [class^=\'backdrop-\'] + [class^=\'modal-\'] [class^=\'topSectionPlaying-\'] {",
	"    background-color: #5294E2 !important; }",
	"  [class^=\'backdrop-\'] + [class^=\'modal-\'] [class^=\'body-\'] {",
	"    background-color: #222D32 !important; }",
	"  [class^=\'backdrop-\'] + [class^=\'modal-\'] [class*=\'tiles-\'] {",
	"    background-color: #1B2428 !important; }",
	"  [class^=\'backdrop-\'] + [class^=\'modal-\'] [class*=\'selectorButtonSelected-\'] {",
	"    background-color: #5294E2 !important; }",
	"  [class^=\'backdrop-\'] + [class^=\'modal-\'] [class^=\'userInfoSectionHeader-\'] {",
	"    color: #d8d8d8 !important; }",
	"  [class^=\'backdrop-\'] + [class^=\'modal-\'] [class*=\'footer-\'] {",
	"    background-color: #1B2428 !important; }",
	"  [class^=\'backdrop-\'] + [class^=\'modal-\'] [name^=\'Nitro\'] path {",
	"    fill: #5294E2 !important; }",
	"  [class^=\'backdrop-\'] + [class^=\'modal-\'] [class^=\'inputDefault-\'] {",
	"    background-color: #1B2428 !important;",
	"    border-color: #1B2428 !important; }",
	"    [class^=\'backdrop-\'] + [class^=\'modal-\'] [class^=\'inputDefault-\']:focus {",
	"      border-color: #5294E2 !important; }",
	"",
	"  .ui-standard-sidebar-view .sidebar-region {",
	"    background-color: #222D32 !important; }",
	"  .ui-standard-sidebar-view .content-region {",
	"    background-color: #263238 !important; }",
	"  .ui-standard-sidebar-view [class*=\'input-\']:not(.input-sensitivity-note) {",
	"    background-color: #222D32 !important;",
	"    border-color: #222D32 !important; }",
	"    .ui-standard-sidebar-view [class*=\'input-\']:not(.input-sensitivity-note):hover, .ui-standard-sidebar-view [class*=\'input-\']:not(.input-sensitivity-note):focus {",
	"      border-color: #5294E2 !important; }",
	"  .ui-standard-sidebar-view [class*=\'title-\']:not([style*=\'color\']) {",
	"    color: #d8d8d8 !important; }",
	"",
	"  [class^=\'side-\'] [class^=\'itemSelected-\']:not([style*=\'background-color\']) {",
	"    background-color: #5294E2 !important;",
	"    color: #fff !important; }",
	"",
	"  [class*=\'cardPrimary-\'],",
	"  [class*=\'cardPrimaryEditable-\'] {",
	"    background-color: #1B2428 !important;",
	"    border-color: #1B2428 !important; }",
	"",
	"  [class*=\'cardPrimaryOutline\'] {",
	"    background-color: #222D32 !important;",
	"    border-color: #222D32 !important; }",
	"",
	"  [class^=\'questionMark-\'] {",
	"    background-color: #5294E2 !important; }",
	"",
	"  [class*=\'accountBtnInner-\'] {",
	"    background-color: #263238 !important;",
	"    border-color: #263238 !important; }",
	"    [class*=\'accountBtnInner-\']:hover {",
	"      border-color: #5294E2 !important; }",
	"",
	"  [class*=\'keybindGroup-\']::before,",
	"  .game::before,",
	"  .invite-settings-invite-row::before,",
	"  .emoji-row::before,",
	"  [class*=\'member-\']::before,",
	"  .guild-settings-banned-user::before {",
	"    background-color: #222D32 !important;",
	"    border-color: #222D32 !important; }",
	"",
	"  [class*=\'keybindGroups-\'] [class^=\'flex-\']:last-child {",
	"    background-color: #222D32 !important; }",
	"",
	"  [class*=\'removeKeybind-\'],",
	"  .remove-game,",
	"  .revoke-invite,",
	"  [class^=\'removeOverride-\'],",
	"  .emoji-remove,",
	"  [class^=\'removeWebhook-\'] {",
	"    background-color: #1B2428 !important;",
	"    border-color: #1B2428 !important; }",
	"",
	"  .game-name-input:hover,",
	"  .game-name-input:focus {",
	"    background-color: #1B2428 !important;",
	"    border-color: #1B2428 !important; }",
	"",
	"  .add-game-popout {",
	"    background-color: #222D32 !important; }",
	"",
	"  [class*=\'auditLog-\'] {",
	"    border-color: #222D32 !important; }",
	"    [class*=\'auditLog-\'] [class^=\'divider-\'] {",
	"      background-color: #1B2428 !important; }",
	"",
	"  [class*=\'headerClickable-\'],",
	"  [class*=\'headerDefault\'] {",
	"    background-color: #222D32 !important; }",
	"",
	"  [class*=\'headerExpanded-\'] {",
	"    background-color: #1B2428 !important; }",
	"",
	"  [class*=\'changeDetails-\'] {",
	"    background-color: #222D32 !important; }",
	"",
	"  [class*=\'colorPickerCustom-\'] {",
	"    background: #222D32 !important;",
	"    border-color: #1B2428 !important; }",
	"    [class*=\'colorPickerCustom-\'] [class*=\'input-\'] {",
	"      background-color: #1B2428 !important;",
	"      border-color: #1B2428 !important; }",
	"      [class*=\'colorPickerCustom-\'] [class*=\'input-\']:focus {",
	"        border-color: #5294E2 !important; }",
	"",
	"  .notice-region [class^=\'container-\'] {",
	"    background-color: #1B2428 !important; }"
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
