[server]
port = 2020
data_dir = "/home/glados/Videos/YouTube"

[tokens]
youtube = ""

[feeds]
  [feeds.Fullsauce]
  url = "https://www.youtube.com/channel/UC2_IYqb1Tc_8Azh7rByedPA"
  page_size = 8
  update_period = "10m"
  quality = "high"
  format = "video"
  max_height = 480
  clean = { keep_last = 6 }
  filters = { not_title = "Vinesauce Art Corner"}

  [feeds.CrowVOD]
  url = "https://www.youtube.com/channel/UCJDDY5VgK2jN5MFK3fHIMbA"
  page_size = 3
  update_period = "10m"
  quality = "high"
  format = "video"
  max_height = 480
  clean = { keep_last = 3 }

  [feeds.VargFull]
  url = "https://www.youtube.com/channel/UCRNCUBq676nUhXyy8AJzD5w"
  page_size = 3
  update_period = "10m"
  quality = "high"
  format = "video"
  max_height = 480
  clean = { keep_last = 3 }
