# Don't print a new line at the start of the prompt
add_newline = false

[git_branch]
symbol = ""

[character]
style_success = "bright-purple"

[directory]
style = "bold blue"
truncation_length = 0
truncate_to_repo = false


[cmd_duration]
min_time = 500
prefix = ""

[jobs]
disabled = true
