# Don't print a new line at the start of the prompt
add_newline = false

[git_branch]
symbol = ""

[character]
success_symbol = "[❯](bright-purple)"

[directory]
style = "bold blue"
truncation_length = 0
truncate_to_repo = false

[cmd_duration]
min_time = 500
format = "[$duration]($style) "

[jobs]
disabled = true
