add_newline = false

[git_branch]
symbol = ""

[character]
success_symbol = "[❯](bright-purple)"

[directory]
style = "bold blue"
fish_style_pwd_dir_length = 3
truncate_to_repo = false

[cmd_duration]
min_time = 500
format = "[$duration]($style) "

[jobs]
disabled = true

[python]
python_binary = "python3"
