source /usr/share/autojump/autojump.bash
source /usr/share/defaults/etc/profile

# Sensible Bash: https://github.com/mrzool/bash-sensible
source $(which sensible.bash)

#aliases
eval alias $(fish -c alias | cut -d' ' -f2- | sed 's/ /=/' | sed 's/(/$(/g' | sed 's/argv/@/g')

eval "$(starship init bash)"
