#!/usr/bin/fish

echo open (echo $QUTE_URL | sed  's/mobile.twitter.com/nitter.snopyta.org/; s/www.youtube.com/invidio.us/; s/twitter.com/nitter.snopyta.org/; s/www.instagram.com/bibliogram.art/; s/old.reddit.com/removeddit.com/; s/reddit.com/removeddit.com/') >> "$QUTE_FIFO"
