#!/usr/bin/fish
if test -e $QUTE_DATA_DIR/greasemonkey/discord.js
    echo "set qt.args ["blink-settings=darkMode=4"]" >> "$QUTE_FIFO"
    mv $QUTE_DATA_DIR/greasemonkey/discord.js $QUTE_DATA_DIR/greasemonkey/discord.js.bak
    echo "restart" >> $QUTE_FIFO
else
    echo "config-unset qt.args" >> "$QUTE_FIFO"
    mv $QUTE_DATA_DIR/greasemonkey/discord.js.bak $QUTE_DATA_DIR/greasemonkey/discord.js
    echo "restart" >> $QUTE_FIFO
end
